spring.application.name=ECOMM-BACKEND-MAIN

# Server Port
#server.port=8088

## MySQL Configuration
#spring.datasource.url= jdbc:h2:mem:ecommdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.h2.console.enabled=true
#spring.datasource.username= root
#spring.datasource.password= root

#POSTGRESSQL Configuration
spring.datasource.url= jdbc:postgresql://localhost:5432/ecommdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= postgres
spring.datasource.password= root

# tells Spring Boot to delay executing schema or data SQL scripts until after the JPA entities are fully initialized
spring.jpa.defer-datasource-initialization=true

#For Spring Boot 3
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Security Credentials
#spring.security.user.name=akg
#spring.security.user.password=akg

#Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#API Path
server.servlet.context-path=/api